apiVersion: v1
kind: Pod
metadata:
  name: spit-gpu-pod
spec:
  containers:
  - name: spit-gpu-container
    image: tensorflow/tensorflow:latest-gpu
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In # Use NotIn for other types
            values:
            - K40

